import { Navigate, Outlet, Route, Routes } from 'react-router-dom';
import { AppShell, Toasts } from './components';
import { StoreProvider, useStore } from './store';
import { AuthPage, InfoPage, Landing, PublicDoctorProfile, PublicDoctors } from './public-pages';
import { AppointmentDetail, Appointments, Booking, DoctorSearch, DocumentDetail, Documents, History, Messages, Notifications, PatientDoctorProfile, PatientOverview, Settings } from './patient-pages';
import { AdminAudit, AdminOverview, AdminReports, AdminTable, Availability, DoctorCalendar, DoctorMessages, DoctorOverview, DoctorProfile, PatientWorkspace } from './role-pages';
import { ExtendedFeatures } from './extended';
import { DoctorIntakes, IntakeAssistant } from './assistant';
function Protected({area}:{area:'patient'|'doctor'|'admin'}){const {user,role,authLoading}=useStore();if(authLoading)return <main className="auth-loading">Loading your secure workspace…</main>;if(!user)return <Navigate to="/login" replace/>;if(role!==area)return <Navigate to={role==='patient'?'/app':`/${role}`} replace/>;return <AppShell><Outlet/></AppShell>}
function NotFound(){return <main className="not-found"><span>404</span><h1>This page left the orbit.</h1><p>The destination doesn't exist or you don't have access.</p><a className="button primary" href="/">Return home</a></main>}
function RoutedApp(){return <><Routes>
<Route path="/" element={<Landing/>}/><Route path="/doctors" element={<PublicDoctors/>}/><Route path="/doctors/:id" element={<PublicDoctorProfile/>}/><Route path="/login" element={<AuthPage mode="login"/>}/><Route path="/register" element={<AuthPage mode="register"/>}/><Route path="/forgot-password" element={<AuthPage mode="forgot"/>}/><Route path="/help" element={<InfoPage type="help"/>}/><Route path="/privacy" element={<InfoPage type="privacy"/>}/><Route path="/terms" element={<InfoPage type="terms"/>}/>
<Route element={<Protected area="patient"/>}><Route path="/app" element={<PatientOverview/>}/><Route path="/app/assistant" element={<IntakeAssistant/>}/><Route path="/app/doctors" element={<DoctorSearch/>}/><Route path="/app/doctors/:id" element={<PatientDoctorProfile/>}/><Route path="/app/book/:id" element={<Booking/>}/><Route path="/app/appointments" element={<Appointments/>}/><Route path="/app/appointments/:id" element={<AppointmentDetail/>}/><Route path="/app/documents" element={<Documents/>}/><Route path="/app/documents/:id" element={<DocumentDetail/>}/><Route path="/app/messages" element={<Messages/>}/><Route path="/app/history" element={<History/>}/><Route path="/app/notifications" element={<Notifications/>}/><Route path="/app/settings" element={<Settings/>}/></Route>
<Route element={<Protected area="doctor"/>}><Route path="/doctor" element={<DoctorOverview/>}/><Route path="/doctor/intakes" element={<DoctorIntakes/>}/><Route path="/doctor/appointments" element={<Appointments doctorView/>}/><Route path="/doctor/appointments/:id" element={<AppointmentDetail doctorView/>}/><Route path="/doctor/calendar" element={<DoctorCalendar/>}/><Route path="/doctor/availability" element={<Availability/>}/><Route path="/doctor/workspace" element={<PatientWorkspace/>}/><Route path="/doctor/messages" element={<DoctorMessages/>}/><Route path="/doctor/profile" element={<DoctorProfile/>}/><Route path="/doctor/settings" element={<Settings/>}/></Route>
<Route element={<Protected area="admin"/>}><Route path="/admin" element={<AdminOverview/>}/><Route path="/admin/patients" element={<AdminTable kind="Patients"/>}/><Route path="/admin/doctors" element={<AdminTable kind="Doctors"/>}/><Route path="/admin/appointments" element={<AdminTable kind="Appointments"/>}/><Route path="/admin/reports" element={<AdminReports/>}/><Route path="/admin/audit" element={<AdminAudit/>}/><Route path="/admin/jobs" element={<AdminAudit jobs/>}/><Route path="/admin/settings" element={<ExtendedFeatures/>}/></Route><Route path="*" element={<NotFound/>}/></Routes><Toasts/></>}
export function App(){return <StoreProvider><RoutedApp/></StoreProvider>}
