import { FormEvent, useEffect, useRef, useState } from 'react';
import { FirstAidKit, PaperPlaneTilt, ShieldWarning, Sparkle, WarningCircle } from '@phosphor-icons/react';
import { Button, Empty, SectionHead } from './components';
import { useStore } from './store';
import { confirmIntake, getDoctorIntakes, markIntakeReviewed, sendIntakeMessage, type Intake } from './services/ai';

type ChatMessage={role:'assistant'|'patient';text:string};
export function IntakeAssistant(){
 const {appointments,notify}=useStore(); const [session]=useState(()=>crypto.randomUUID().replaceAll('-','')); const [draft,setDraft]=useState(''); const [messages,setMessages]=useState<ChatMessage[]>([{role:'assistant',text:'Hello â€” I can help organize synthetic test information for your doctor. What would you like to discuss today? Ø§Ø±Ø¯Ùˆ Ù…ÛŒÚº Ø¨Ú¾ÛŒ Ø¬ÙˆØ§Ø¨ Ø¯Û’ Ø³Ú©ØªÛ’ ÛÛŒÚºÛ”'}]); const [intake,setIntake]=useState<Intake>(); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const controller=useRef<AbortController | undefined>(undefined);
 async function send(e:FormEvent){e.preventDefault();const message=draft.trim();if(!message||busy)return;setMessages(v=>[...v,{role:'patient',text:message}]);setDraft('');setBusy(true);setError('');controller.current=new AbortController();try{const result=await sendIntakeMessage(session,message,appointments[0]?.id,controller.current.signal);setMessages(v=>[...v,{role:'assistant',text:result.message}]);setIntake(result.intake)}catch(err){setError(err instanceof Error?err.message:'Assistant unavailable')}finally{setBusy(false)}}
 async function submit(share:boolean){if(!intake)return;setBusy(true);setError('');try{const saved=await confirmIntake(intake.intake_id,appointments[0]?.id,share);setIntake(saved);notify(share?'Confirmed and shared with your assigned doctor':'Intake confirmed privately')}catch(err){setError(err instanceof Error?err.message:'Could not confirm intake')}finally{setBusy(false)}}
 return <div className="stack"><SectionHead title="AI intake assistant" subtitle="Organize symptoms before a visit â€” without diagnosis or treatment advice."/><div className="dev-warning"><ShieldWarning/><div><strong>Synthetic development data only</strong><p>Messages are sent to Groq for AI processing. Do not enter real patient information, names, addresses, IDs, or payment details.</p></div></div><div className="intake-layout"><section className="panel intake-chat"><div className="messages" aria-live="polite">{messages.map((m,i)=><div key={i} className={`bubble ${m.role==='patient'?'me':''}`} dir="auto"><p>{m.text}</p></div>)}{busy?<div className="bubble"><p>Organizing your informationâ€¦</p></div>:null}</div>{error?<div className="form-error" role="alert">{error}</div>:null}<form className="composer" onSubmit={send}><textarea value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Describe one concern at a timeâ€¦" aria-label="Message for intake assistant" maxLength={3000}/><button className="send" disabled={busy||!draft.trim()} aria-label="Send"><PaperPlaneTilt weight="fill"/></button></form><small className="intake-fineprint">Not for emergencies. If you may be in immediate danger, contact local emergency services now.</small></section><aside className="panel intake-summary"><span className="eyebrow"><Sparkle/> Live summary</span>{!intake?<Empty icon={<FirstAidKit/>} title="Your summary will build here" text="The assistant records only what you state and clearly marks unknown or skipped details."/>:<><h3>{intake.chief_concern||'Concern being clarified'}</h3><Summary label="Symptoms" items={intake.symptoms}/><Summary label="Associated details" items={intake.associated_symptoms}/><Summary label="Medications" items={intake.medications}/><Summary label="Allergies" items={intake.allergies}/><Summary label="Unknown or skipped" items={intake.unknown_or_skipped}/>{intake.potential_urgent_concern?<div className="urgent-card"><WarningCircle/><strong>Potential urgent concern â€” seek immediate local care.</strong></div>:null}{intake.status==='awaiting_patient_confirmation'?<div className="confirm-box"><strong>Does this accurately reflect what you shared?</strong><p>Confirming does not make this a diagnosis.</p><Button disabled={busy} onClick={()=>submit(false)}>Confirm privately</Button><Button variant="secondary" disabled={busy||!appointments.length} onClick={()=>submit(true)}>Confirm & share with doctor</Button>{!appointments.length?<small>A confirmed appointment is required to share.</small>:null}</div>:null}{['submitted','reviewed'].includes(intake.status)?<div className="success-card">Confirmed Â· {intake.status==='reviewed'?'Reviewed by doctor':'Ready for review'}</div>:null}</>}</aside></div></div>
}
function Summary({label,items}:{label:string;items:string[]}){return items.length?<div className="summary-block"><strong>{label}</strong><ul>{items.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul></div>:null}

export function DoctorIntakes(){const [items,setItems]=useState<Intake[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');useEffect(()=>{getDoctorIntakes().then(setItems).catch(e=>setError(e instanceof Error?e.message:'Unable to load')).finally(()=>setLoading(false))},[]);async function review(item:Intake){try{const next=await markIntakeReviewed(item.intake_id,'Reviewed in CareOrbit');setItems(v=>v.map(x=>x.intake_id===next.intake_id?next:x))}catch(e){setError(e instanceof Error?e.message:'Unable to review')}}return <div className="stack"><SectionHead title="Patient intake handoffs" subtitle="Only patient-confirmed summaries explicitly shared with your account."/>{error?<div className="form-error">{error}</div>:null}<section className="panel">{loading?<p>Loading authorized summariesâ€¦</p>:!items.length?<Empty title="No shared intakes" text="Patient-confirmed intake summaries will appear here after consent and appointment checks."/>:items.map(item=><article className="intake-review" key={item.intake_id}><div><span className="badge">{item.status}</span><h3>{item.chief_concern||'Patient concern'}</h3><p>{item.patient_confirmed_summary}</p><Summary label="Symptoms" items={item.symptoms}/></div><Button variant="secondary" disabled={item.status==='reviewed'} onClick={()=>review(item)}>{item.status==='reviewed'?'Reviewed':'Mark reviewed'}</Button></article>)}</section></div>}

