import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { ArrowRight, CalendarCheck, Check, Clock, FileText, Heartbeat, MagnifyingGlass, ShieldCheck, Sparkle, Stethoscope, Users } from '@phosphor-icons/react';
import { doctors } from './data';
import { Button, Logo } from './components';
import { useStore } from './store';
import type { Role } from './domain';

export function PublicHeader() { return <header className="public-header"><Logo/><nav><Link to="/doctors">Find a doctor</Link><Link to="/help">Help</Link></nav><div><Link className="text-link" to="/login">Sign in</Link><Link className="button primary" to="/register">Create account</Link></div></header>; }
export function Landing() { const navigate = useNavigate(); const [query, setQuery] = useState(''); return <><PublicHeader/><main className="landing">
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck/> Trusted care, thoughtfully connected</span><h1>Your health care, <em>in one orbit.</em></h1><p>Find verified doctors, book with confidence, understand your documents, and keep your care journey organized.</p><form className="search-box" onSubmit={e => { e.preventDefault(); navigate(`/doctors?q=${encodeURIComponent(query)}`); }}><MagnifyingGlass/><input value={query} onChange={e => setQuery(e.target.value)} aria-label="Search doctors" placeholder="Specialty, doctor, or location"/><Button>Find care <ArrowRight/></Button></form><div className="trust-row"><span><Check/> Verified providers</span><span><Check/> Private records</span><span><Check/> Clear appointment times</span></div></div>
  <div className="hero-panel"><div className="orbit-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-center"><Heartbeat weight="fill"/></div><div className="float-card fc-one"><span className="mini-avatar">AK</span><div><strong>Dr. Ayesha Khan</strong><small>Cardiology · Verified</small></div></div><div className="float-card fc-two"><CalendarCheck/><div><strong>Appointment confirmed</strong><small>Saturday · 10:30 AM PKT</small></div></div><div className="float-card fc-three"><FileText/><div><strong>Summary ready</strong><small>Source-linked and reviewable</small></div></div></div></div></section>
  <section className="proof"><span>One calm place for</span><strong>Appointments</strong><strong>Medical documents</strong><strong>Care conversations</strong><strong>Visit history</strong></section>
  <section className="how"><div><span className="eyebrow">A clearer path to care</span><h2>From search to follow-up, without the usual friction.</h2></div><ol><li><span>01</span><Stethoscope/><h3>Find the right doctor</h3><p>Filter verified providers by specialty, location, fee, language, experience, and real availability.</p></li><li><span>02</span><CalendarCheck/><h3>Book a real slot</h3><p>Review the clinic, fee, timezone, and cancellation policy before confirming.</p></li><li><span>03</span><Sparkle/><h3>Stay oriented</h3><p>Keep documents, messages, reminders, and source-grounded AI summaries together.</p></li></ol></section>
  <section className="paths"><div><Users/><span>For patients</span><h2>Your care journey, organized around you.</h2><p>Appointments, records, summaries, and conversations—accessible wherever you are.</p><Link to="/register">Create a patient account <ArrowRight/></Link></div><div><Stethoscope/><span>For providers</span><h2>Clinical workflows with clearer boundaries.</h2><p>Manage availability, consult from authorized context, and keep follow-up focused.</p><Link to="/register?role=doctor">Apply as a doctor <ArrowRight/></Link></div></section>
  <section className="ai-note"><Sparkle/><div><strong>AI that explains, never diagnoses.</strong><p>CareOrbit summaries help you navigate what your document says, with source references and limitations. They are informational only and never replace a clinician.</p></div></section>
  </main><footer><Logo/><p>CareOrbit is a portfolio demonstration using fictional information. Not for emergency or clinical use.</p><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/help">Help</Link></div></footer></>;
}

export function PublicDoctors() { const [term,setTerm] = useState(''); const [specialty,setSpecialty] = useState('All specialties'); const list = doctors.filter(d => (d.name+d.specialty+d.location).toLowerCase().includes(term.toLowerCase()) && (specialty === 'All specialties' || d.specialty === specialty)); return <><PublicHeader/><main className="public-page"><div className="directory-head"><span className="eyebrow">Verified care in Lahore</span><h1>Find a doctor who fits your needs.</h1><p>Availability is shown in Asia/Karachi (PKT).</p></div><div className="filter-bar"><label><MagnifyingGlass/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search doctor or location"/></label><select aria-label="Specialty" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option>All specialties</option>{[...new Set(doctors.map(d=>d.specialty))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Language"><option>Any language</option><option>English</option><option>Urdu</option></select></div><p className="result-count">{list.length} verified doctors</p><div className="doctor-grid">{list.map(d=><article className="doctor-card" key={d.id}><div className="doctor-avatar">{d.name.split(' ').slice(-1)[0][0]}{d.name.split(' ')[1][0]}</div><div className="doctor-main"><span className="verified"><ShieldCheck weight="fill"/> Verified</span><h2>{d.name}</h2><strong>{d.specialty}</strong><p>{d.qualification} · {d.experience} years</p><p>{d.languages.join(', ')} · {d.location}</p><div className="availability"><Clock/><span>Next available<strong>{d.nextSlot}</strong></span></div><div className="doctor-actions"><span><small>Consultation fee</small><strong>PKR {d.fee.toLocaleString()}</strong></span><Link className="button secondary" to={`/doctors/${d.id}`}>View profile</Link><Link className="button primary" to={`/doctors/${d.id}?book=1`}>Book</Link></div></div></article>)}</div></main></> }

export function PublicDoctorProfile() { const { id } = useParams(); const doctor = doctors.find(d=>d.id===id) ?? doctors[0]; const navigate=useNavigate(); return <><PublicHeader/><main className="public-page"><Link className="back-link" to="/doctors">← Back to results</Link><div className="profile-layout"><section className="profile-card"><div className="doctor-avatar large">AK</div><span className="verified"><ShieldCheck weight="fill"/> Identity and license verified</span><h1>{doctor.name}</h1><h2>{doctor.specialty}</h2><p>{doctor.qualification} · {doctor.experience} years of experience</p><div className="profile-facts"><span><strong>Languages</strong>{doctor.languages.join(', ')}</span><span><strong>Consultation</strong>{doctor.mode}</span><span><strong>Location</strong>{doctor.location}</span><span><strong>Fee</strong>PKR {doctor.fee.toLocaleString()}</span></div><hr/><h3>About</h3><p>{doctor.bio}</p><h3>Care location</h3><p>Gulberg Medical Centre · Lahore · Asia/Karachi (PKT)</p></section><aside className="booking-panel"><h2>Choose a time</h2><p>Saturday, 10 October · PKT</p><div className="date-strip">{['Fri 09','Sat 10','Sun 11','Mon 12'].map((d,i)=><button className={i===1?'selected':''} key={d}>{d}</button>)}</div><h3>Morning</h3><div className="slot-grid">{['9:00 AM','10:30 AM','11:15 AM'].map((t,i)=><button disabled={i===0} key={t}>{t}</button>)}</div><h3>Afternoon</h3><div className="slot-grid"><button>2:00 PM</button><button>3:30 PM</button></div><Button onClick={()=>navigate('/login?next=booking')}>Continue to book</Button><small>Submitting reserves the slot as Scheduled until the doctor confirms.</small></aside></div></main></> }

export function AuthPage({ mode }: { mode:'login'|'register'|'forgot' }) { const { login, notify } = useStore(); const navigate=useNavigate(); const [role,setRole]=useState<Role>('patient'); const [sent,setSent]=useState(false); function submit(e:FormEvent){e.preventDefault(); if(mode==='forgot'){setSent(true);return;} login(role); notify(mode==='login'?'Welcome back to CareOrbit':'Your demo account is ready'); navigate(role==='patient'?'/app':`/${role}`)} return <main className="auth-page"><section className="auth-brand"><Logo/><div><span className="eyebrow">Care that stays connected</span><h1>A calmer way to manage your health journey.</h1><p>Secure appointments, documents, messages, and visit history in one thoughtful workspace.</p></div><small>Demo environment · fictional data only</small></section><section className="auth-form"><div>{sent?<div className="auth-success"><div className="success-icon"><Check/></div><h1>Check your inbox</h1><p>If an account exists for that email, we sent password reset instructions.</p><Link className="button primary" to="/login">Back to sign in</Link></div>:<><span className="eyebrow">Welcome to CareOrbit</span><h1>{mode==='login'?'Sign in to your account':mode==='register'?'Create your account':'Reset your password'}</h1><p>{mode==='forgot'?'Enter your email and we’ll send secure instructions.':'Use the demo form to explore the complete portal.'}</p><form onSubmit={submit}>{mode!=='forgot'?<label>Account type<select value={role} onChange={e=>setRole(e.target.value as Role)}><option value="patient">Patient</option><option value="doctor">Doctor</option>{mode==='login'?<option value="admin">Administrator</option>:null}</select></label>:null}{mode==='register'?<label>Full name<input required minLength={2} placeholder="Your full name"/></label>:null}<label>Email address<input required type="email" defaultValue={mode==='login'?'sara@example.com':''} placeholder="you@example.com"/></label>{mode!=='forgot'?<label>Password<input required type="password" defaultValue={mode==='login'?'demo12345':''} minLength={8}/></label>:null}<Button type="submit">{mode==='login'?'Sign in':mode==='register'?'Create account':'Send reset instructions'} <ArrowRight/></Button></form><div className="auth-links">{mode==='login'?<><Link to="/forgot-password">Forgot password?</Link><span>New to CareOrbit? <Link to="/register">Create account</Link></span></>:<Link to="/login">Back to sign in</Link>}</div></>}</div></section></main> }

export function InfoPage({ type }: { type:string }) { const copy:Record<string,[string,string]>= { help:['How can we help?','CareOrbit support can help with account access, appointments, documents, and privacy requests. For emergencies, contact your local emergency service.'], privacy:['Privacy comes first.','CareOrbit collects only what is needed to deliver your care workflows. Medical files are private, sharing is explicit, and AI processing requires separate consent.'], terms:['Clear terms for safer care.','CareOrbit is not an emergency service. AI summaries are informational and do not diagnose, prescribe, or replace professional medical advice.'] }; const [title,text]=copy[type]??copy.help; return <><PublicHeader/><main className="legal-page"><span className="eyebrow">CareOrbit {type}</span><h1>{title}</h1><p>{text}</p><section><h2>Important information</h2><p>This portfolio build uses synthetic data. Production policies, retention periods, jurisdiction, third-party providers, and clinical approvals must be finalized before real patient use.</p></section></main></> }
