import { useState, type FormEvent } from 'react';
import { Link, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { ArrowRight, CalendarCheck, Check, Clock, FileText, Heartbeat, MagnifyingGlass, ShieldCheck, Sparkle, Stethoscope, Users } from '@phosphor-icons/react';
import { useDoctors } from './services/use-doctors';
import { Button, Logo } from './components';
import { useStore } from './store';
import { loginWithEmail, registerWithEmail, resetPassword, signInWithGoogle } from './services/auth';
import type { Role } from './domain';

export function PublicHeader() { return <header className="public-header"><Logo/><nav><Link to="/doctors">Find a doctor</Link><Link to="/help">Help</Link></nav><div><Link className="text-link" to="/login">Sign in</Link><Link className="button primary" to="/register">Create account</Link></div></header>; }
export function Landing() { const navigate = useNavigate(); const [query, setQuery] = useState(''); return <><PublicHeader/><main className="landing">
  <section className="hero"><div className="hero-copy"><span className="eyebrow"><ShieldCheck/> Trusted care, thoughtfully connected</span><h1>Your health care, <em>in one orbit.</em></h1><p>Find verified doctors, book with confidence, understand your documents, and keep your care journey organized.</p><form className="search-box" onSubmit={e => { e.preventDefault(); navigate(`/doctors?q=${encodeURIComponent(query)}`); }}><MagnifyingGlass/><input value={query} onChange={e => setQuery(e.target.value)} aria-label="Search doctors" placeholder="Specialty, doctor, or location"/><Button>Find care <ArrowRight/></Button></form><div className="trust-row"><span><Check/> Verified providers</span><span><Check/> Private records</span><span><Check/> Clear appointment times</span></div></div>
  <div className="hero-panel"><div className="orbit-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="orbit-center"><Heartbeat weight="fill"/></div><div className="float-card fc-one"><span className="mini-avatar">AK</span><div><strong>Dr. Ayesha Khan</strong><small>Cardiology · Verified</small></div></div><div className="float-card fc-two"><CalendarCheck/><div><strong>Appointment confirmed</strong><small>Saturday · 10:30 AM PKT</small></div></div><div className="float-card fc-three"><FileText/><div><strong>Summary ready</strong><small>Source-linked and reviewable</small></div></div></div></div></section>
  <section className="proof"><span>One calm place for</span><strong>Appointments</strong><strong>Medical documents</strong><strong>Care conversations</strong><strong>Visit history</strong></section>
  <section className="how"><div><span className="eyebrow">A clearer path to care</span><h2>From search to follow-up, without the usual friction.</h2></div><ol><li><span>01</span><Stethoscope/><h3>Find the right doctor</h3><p>Filter verified providers by specialty, location, fee, language, experience, and real availability.</p></li><li><span>02</span><CalendarCheck/><h3>Book a real slot</h3><p>Review the clinic, fee, timezone, and cancellation policy before confirming.</p></li><li><span>03</span><Sparkle/><h3>Stay oriented</h3><p>Keep documents, messages, reminders, and source-grounded AI summaries together.</p></li></ol></section>
  <section className="paths"><div><Users/><span>For patients</span><h2>Your care journey, organized around you.</h2><p>Appointments, records, summaries, and conversations—accessible wherever you are.</p><Link to="/register">Create a patient account <ArrowRight/></Link></div><div><Stethoscope/><span>For providers</span><h2>Clinical workflows with clearer boundaries.</h2><p>Manage availability, consult from authorized context, and keep follow-up focused.</p><Link to="/register?role=doctor">Apply as a doctor <ArrowRight/></Link></div></section>
  <section className="story-section"><div className="story-intro"><span className="eyebrow">The care journey, reconnected</span><h2>Healthcare rarely happens in one moment. Your portal shouldn't treat it that way.</h2><p>A symptom starts on Tuesday. A report arrives on Thursday. The appointment is next week. CareOrbit keeps the thread intact—so you spend less time reconstructing what happened and more time moving forward with clarity.</p></div><div className="story-steps"><article><span>Before the visit</span><h3>Find care without guesswork.</h3><p>Compare verified doctors using the details that actually shape a decision: real availability, location, language, experience, consultation mode, and fee.</p></article><article><span>When context matters</span><h3>Share the right record—not your whole history.</h3><p>Choose each document, recipient, and purpose. AI processing is a separate consent, and every summary points back to its source.</p></article><article><span>After the appointment</span><h3>Leave with a path you can follow.</h3><p>Return to published visit summaries, secure messages, reminders, and document history without searching across inboxes and paper files.</p></article></div></section>
  <section className="trust-story"><div><span className="eyebrow">Built around a simple promise</span><h2>Your care should feel connected. Your data should remain yours.</h2></div><div><p>CareOrbit brings patients and verified providers into one focused workspace while keeping clinical boundaries visible. Doctors see only authorized context. Administrators manage operations without routine access to medical content. AI explains source material but never diagnoses or prescribes.</p><div className="trust-points"><span><ShieldCheck/> Explicit sharing controls</span><span><Check/> Role-protected workspaces</span><span><Sparkle/> Source-linked AI summaries</span></div></div></section>  <section className="ai-note"><Sparkle/><div><strong>AI that explains, never diagnoses.</strong><p>CareOrbit summaries help you navigate what your document says, with source references and limitations. They are informational only and never replace a clinician.</p></div></section>
  <section className="bottom-cta"><span className="eyebrow">Ready when you are</span><h2>Put every next step in one clear place.</h2><p>Start as a patient, or apply to join CareOrbit as a verified provider.</p><div><Link className="button primary" to="/register?role=patient">Create patient account <ArrowRight/></Link><Link className="button secondary" to="/register?role=doctor">Apply as a doctor</Link></div><small>Already have an account? <Link to="/login">Sign in to your portal</Link></small></section>  </main><footer><Logo/><p>CareOrbit does not preload fictional clinical records. Not for emergency use.</p><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/help">Help</Link></div></footer></>;
}

export function PublicDoctors() { const { doctors } = useDoctors(); const [term,setTerm] = useState(''); const [specialty,setSpecialty] = useState('All specialties'); const list = doctors.filter(d => (d.name+d.specialty+d.location).toLowerCase().includes(term.toLowerCase()) && (specialty === 'All specialties' || d.specialty === specialty)); return <><PublicHeader/><main className="public-page"><div className="directory-head"><span className="eyebrow">Verified care in Lahore</span><h1>Find a doctor who fits your needs.</h1><p>Availability is shown in Asia/Karachi (PKT).</p></div><div className="filter-bar"><label><MagnifyingGlass/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Search doctor or location"/></label><select aria-label="Specialty" value={specialty} onChange={e=>setSpecialty(e.target.value)}><option>All specialties</option>{[...new Set(doctors.map(d=>d.specialty))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Language"><option>Any language</option><option>English</option><option>Urdu</option></select></div><p className="result-count">{list.length} verified doctors</p><div className="doctor-grid">{list.map(d=><article className="doctor-card" key={d.id}><div className="doctor-avatar">{d.name.split(' ').slice(-1)[0][0]}{d.name.split(' ')[1][0]}</div><div className="doctor-main"><span className="verified"><ShieldCheck weight="fill"/> Verified</span><h2>{d.name}</h2><strong>{d.specialty}</strong><p>{d.qualification} · {d.experience} years</p><p>{d.languages.join(', ')} · {d.location}</p><div className="availability"><Clock/><span>Next available<strong>{d.nextSlot}</strong></span></div><div className="doctor-actions"><span><small>Consultation fee</small><strong>PKR {d.fee.toLocaleString()}</strong></span><Link className="button secondary" to={`/doctors/${d.id}`}>View profile</Link><Link className="button primary" to={`/doctors/${d.id}?book=1`}>Book</Link></div></div></article>)}</div></main></> }

export function PublicDoctorProfile() { const { id } = useParams(); const { doctors } = useDoctors(); const doctor = doctors.find(d=>d.id===id) ?? doctors[0]; const navigate=useNavigate(); return <><PublicHeader/><main className="public-page"><Link className="back-link" to="/doctors">← Back to results</Link><div className="profile-layout"><section className="profile-card"><div className="doctor-avatar large">AK</div><span className="verified"><ShieldCheck weight="fill"/> Identity and license verified</span><h1>{doctor.name}</h1><h2>{doctor.specialty}</h2><p>{doctor.qualification} · {doctor.experience} years of experience</p><div className="profile-facts"><span><strong>Languages</strong>{doctor.languages.join(', ')}</span><span><strong>Consultation</strong>{doctor.mode}</span><span><strong>Location</strong>{doctor.location}</span><span><strong>Fee</strong>PKR {doctor.fee.toLocaleString()}</span></div><hr/><h3>About</h3><p>{doctor.bio}</p><h3>Care location</h3><p>Gulberg Medical Centre · Lahore · Asia/Karachi (PKT)</p></section><aside className="booking-panel"><h2>Choose a time</h2><p>Saturday, 10 October · PKT</p><div className="date-strip">{['Fri 09','Sat 10','Sun 11','Mon 12'].map((d,i)=><button className={i===1?'selected':''} key={d}>{d}</button>)}</div><h3>Morning</h3><div className="slot-grid">{['9:00 AM','10:30 AM','11:15 AM'].map((t,i)=><button disabled={i===0} key={t}>{t}</button>)}</div><h3>Afternoon</h3><div className="slot-grid"><button>2:00 PM</button><button>3:30 PM</button></div><Button onClick={()=>navigate('/login?next=booking')}>Continue to book</Button><small>Submitting reserves the slot as Scheduled until the doctor confirms.</small></aside></div></main></> }

export function AuthPage({ mode }: { mode:'login'|'register'|'forgot' }) {
  const { setAuthenticatedUser, notify } = useStore(); const navigate = useNavigate(); const [params] = useSearchParams();
  const requested = params.get('role'); const [role,setRole] = useState<Role>(requested === 'doctor' || requested === 'admin' ? requested : 'patient');
  const [name,setName] = useState(''); const [email,setEmail] = useState(''); const [password,setPassword] = useState('');
  const [sent,setSent] = useState(false); const [busy,setBusy] = useState(false); const [error,setError] = useState('');
  const destination = (nextRole: Role) => nextRole === 'patient' ? '/app' : `/${nextRole}`;
  async function submit(e:FormEvent){ e.preventDefault(); setBusy(true); setError(''); try {
    if(mode==='forgot'){ await resetPassword(email); setSent(true); return; }
    const nextUser = mode === 'register' ? await registerWithEmail(name,email,password,role as 'patient'|'doctor') : await loginWithEmail(email,password,role);
    setAuthenticatedUser(nextUser); notify(mode==='login'?'Welcome back to CareOrbit':'Your account is ready. Check your inbox to verify your email.'); navigate(destination(nextUser.role));
  } catch (cause) { setError(cause instanceof Error ? cause.message : 'We could not complete that request. Please try again.'); } finally { setBusy(false); } }
  async function google(){ setBusy(true); setError(''); try { const nextUser = await signInWithGoogle(role,role!=='admin'); setAuthenticatedUser(nextUser); navigate(destination(nextUser.role)); } catch(cause) { const message=cause instanceof Error?cause.message:''; setError(message.toLowerCase().includes('client is offline')?'Google verified your identity, but CareOrbit could not reach Firestore. Create Firestore Database in Firebase Console, then retry.':message||'Google sign-in could not be completed.'); } finally { setBusy(false); } }
  return <main className="auth-page"><section className="auth-brand"><Logo/><div><span className="eyebrow">Care that stays connected</span><h1>One secure account for the moments that shape your care.</h1><p>Book confidently, keep the right records close, and return to every conversation with context.</p></div><small>Private by design · role-protected access</small></section><section className="auth-form"><div>{sent?<div className="auth-success"><div className="success-icon"><Check/></div><h1>Check your inbox</h1><p>If an account exists for that email, Firebase sent secure password reset instructions.</p><Link className="button primary" to="/login">Back to sign in</Link></div>:<><span className="eyebrow">{role} portal</span><h1>{mode==='login'?'Welcome back':mode==='register'?'Start your CareOrbit journey':'Reset your password'}</h1><p>{mode==='forgot'?'Enter your email and we?ll send secure instructions.':role==='doctor'?'Access your schedule, authorized patient context, and care follow-up.':role==='admin'?'Authorized operators only. Admin registration is never public.':'Keep your care journey clear, connected, and in your control.'}</p>{error?<div className="form-error" role="alert">{error}</div>:null}{mode!=='forgot'?<><div className="portal-picker" role="group" aria-label="Choose portal">{(['patient','doctor',...(mode==='login'?['admin']:[])] as Role[]).map(item=><button type="button" className={role===item?'active':''} onClick={()=>setRole(item)} key={item}>{item}</button>)}</div><Button className="google-button" variant="secondary" type="button" disabled={busy} onClick={google}><span className="google-mark">G</span> Continue with Google</Button><div className="or"><span>or continue with email</span></div></>:null}<form onSubmit={submit}>{mode==='register'?<label>Full name<input required minLength={2} value={name} onChange={e=>setName(e.target.value)} autoComplete="name" placeholder="Your full name"/></label>:null}<label>Email address<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="you@example.com"/></label>{mode!=='forgot'?<label>Password<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} minLength={8}/></label>:null}<Button type="submit" disabled={busy}>{busy?'Please wait…':mode==='login'?'Sign in':mode==='register'?'Create secure account':'Send reset instructions'} {!busy?<ArrowRight/>:null}</Button></form><div className="auth-links">{mode==='login'?<><Link to="/forgot-password">Forgot password?</Link><span>New to CareOrbit? <Link to={`/register?role=${role==='admin'?'patient':role}`}>Create account</Link></span></>:<Link to={`/login?role=${role}`}>Back to sign in</Link>}</div></>}</div></section></main>;
}

export function InfoPage({ type }: { type:string }) { const copy:Record<string,[string,string]>= { help:['How can we help?','CareOrbit support can help with account access, appointments, documents, and privacy requests. For emergencies, contact your local emergency service.'], privacy:['Privacy comes first.','CareOrbit collects only what is needed to deliver your care workflows. Medical files are private, sharing is explicit, and AI processing requires separate consent.'], terms:['Clear terms for safer care.','CareOrbit is not an emergency service. AI summaries are informational and do not diagnose, prescribe, or replace professional medical advice.'] }; const [title,text]=copy[type]??copy.help; return <><PublicHeader/><main className="legal-page"><span className="eyebrow">CareOrbit {type}</span><h1>{title}</h1><p>{text}</p><section><h2>Important information</h2><p>No clinical records are preloaded in this build. Production policies, retention periods, jurisdiction, third-party providers, and clinical approvals must be finalized before real patient use.</p></section></main></> }
