import { Link } from 'react-router-dom';
import { CalendarBlank, CaretRight, Clock, FileText, ShieldCheck, Stethoscope, Users } from '@phosphor-icons/react';
import { Appointments, Messages, Settings } from './patient-pages';
import { Badge, Button, Empty, Metric, SectionHead } from './components';
import { useStore } from './store';

export function DoctorOverview(){const {user,appointments}=useStore();const pending=appointments.filter(a=>a.status==='Scheduled').length;const completed=appointments.filter(a=>a.status==='Completed').length;return <div className="stack"><div className="welcome"><div><span className="eyebrow">Doctor workspace</span><h2>Good morning, {user?.name}.</h2><p>Your live schedule and authorized care tasks appear here.</p></div><Link className="button secondary" to="/doctor/availability">Manage availability</Link></div><div className="metrics"><Metric icon={<CalendarBlank/>} label="Appointments" value={String(appointments.length)} detail="Loaded from Firestore"/><Metric icon={<Clock/>} label="Awaiting confirmation" value={String(pending)} detail={pending?'Review pending requests':'Nothing awaiting review'}/><Metric icon={<Users/>} label="Completed" value={String(completed)} detail="Your accessible appointment history"/></div><section className="panel table-panel"><SectionHead title="Schedule" subtitle="Only appointments assigned to your account"/><table><thead><tr><th>Patient</th><th>Date & time</th><th>Reason</th><th>Status</th><th></th></tr></thead><tbody>{appointments.map(a=><tr key={a.id}><td>{a.patientName}</td><td>{a.date} · {a.time}</td><td>{a.reason}</td><td><Badge status={a.status}/></td><td><Link to={`/doctor/appointments/${a.id}`}>Open <CaretRight/></Link></td></tr>)}</tbody></table>{!appointments.length?<Empty title="No appointments yet" text="Confirmed relationships and appointment requests will appear here."/>:null}</section></div>}
export { Appointments as DoctorAppointments };
export function DoctorCalendar(){const {appointments}=useStore();return <div className="stack"><SectionHead title="Calendar" subtitle="Live appointments from Firestore"/>{appointments.length?<div className="panel">{appointments.map(a=><Link className="list-row" to={`/doctor/appointments/${a.id}`} key={a.id}><CalendarBlank/><div><strong>{a.patientName}</strong><small>{a.date} · {a.time} · {a.mode}</small></div><Badge status={a.status}/><CaretRight/></Link>)}</div>:<div className="panel"><Empty title="Your calendar is clear" text="Appointments will appear here when patients book available slots."/></div>}</div>}
export function Availability(){const {notify}=useStore();return <div className="stack"><SectionHead title="Availability" subtitle="Availability persistence requires the protected scheduling function."/><section className="panel"><Empty icon={<Clock/>} title="No availability rules published" text="Connect the scheduling Cloud Function to publish conflict-safe working hours." action={<Button onClick={()=>notify('Scheduling function must be deployed before availability can be published','info')}>Set up scheduling</Button>}/></section></div>}
export function PatientWorkspace(){const {appointments}=useStore();const active=appointments.find(a=>['Scheduled','Confirmed'].includes(a.status));return <div className="stack"><SectionHead title="Patient workspace" subtitle="Opens only within an authorized appointment relationship."/>{active?<section className="panel"><h2>{active.patientName}</h2><p>{active.date} · {active.time} · {active.reason}</p><div className="policy"><ShieldCheck/><p>Only records explicitly granted for this appointment may be displayed.</p></div><Link className="button primary" to={`/doctor/appointments/${active.id}`}>Open appointment</Link></section>:<section className="panel"><Empty title="No authorized patient context" text="A confirmed appointment is required before a patient workspace can be opened."/></section>}</div>}
export function DoctorProfile(){const {user,notify}=useStore();return <div className="stack"><SectionHead title="Profile & clinics" subtitle="Complete your provider profile before requesting verification."/><form className="panel settings-form" onSubmit={e=>{e.preventDefault();notify('Profile submission requires the protected provider-profile function','info')}}><div className="form-grid"><label>Display name<input defaultValue={user?.name}/></label><label>Email<input value={user?.email??''} readOnly/></label><label>Primary specialty<input placeholder="Your specialty"/></label><label>Qualifications<input placeholder="Degrees and credentials"/></label><label>Experience<input type="number" min="0"/></label><label>Consultation fee<input type="number" min="0"/></label></div><label>Biography<textarea placeholder="Describe your practice and approach to care."/></label><Button type="submit">Save profile</Button></form></div>}
export function AdminOverview(){const {appointments}=useStore();const completed=appointments.filter(a=>a.status==='Completed').length;const rate=appointments.length?`${((completed/appointments.length)*100).toFixed(1)}%`:'0%';return <div className="stack"><SectionHead title="Platform health" subtitle="Live operational data available to this admin account."/><div className="metrics"><Metric icon={<CalendarBlank/>} label="Appointments" value={String(appointments.length)} detail="Accessible Firestore records"/><Metric icon={<Stethoscope/>} label="Completion rate" value={rate} detail="Completed ÷ all statuses"/><Metric icon={<ShieldCheck/>} label="Clinical content" value="Restricted" detail="Not exposed in operational analytics"/></div><section className="panel"><Empty title="Aggregate reporting is ready for backend aggregation" text="Deploy trusted aggregate functions to calculate patient, provider, specialty, and delivery metrics without exposing clinical records."/></section></div>}
export function AdminTable({kind}:{kind:string}){return <div className="stack"><SectionHead title={kind} subtitle="Firestore-backed operational records only."/><section className="panel"><Empty title={`No ${kind.toLowerCase()} available`} text="Records will appear after authorized backend operations create them."/></section></div>}
export function AdminReports(){return <div className="stack"><SectionHead title="Reports" subtitle="Privacy-safe aggregate reporting."/><section className="panel"><Empty title="No report data yet" text="Deploy aggregate Cloud Functions to populate cohort-defined reporting."/></section></div>}
export function AdminAudit({jobs=false}:{jobs?:boolean}){return <div className="stack"><SectionHead title={jobs?'Processing & delivery jobs':'Audit log'} subtitle="Server-generated records only."/><section className="panel"><Empty icon={<FileText/>} title={jobs?'No processing jobs':'No audit events'} text="Trusted backend events will appear here when available."/></section></div>}
export function GenericSettings(){return <Settings/>}
export function DoctorMessages(){return <Messages doctorView/>}